theme: jekyll-theme-minimal

title: AoE
description: AoE (AI on Edge) 是一个终端侧AI集成运行时环境 (IRE)，帮助开发者提升效率。

logo: https://img0.didiglobal.com/static/gstar/img/AwRPnWCJkW1577246025490.png
show_downloads: true