name: Android CI

on: [push]

jobs:
  check:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v1
    - name: Build with Gradle
      run: |
        cd ./Android
        ./gradlew clean check --profile
